# Multi-stage build para Producción Frontend (Angular SPA + Nginx)
FROM node:20-bookworm-slim AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa 2: Servidor Nginx ultra ligero y optimizado
FROM nginx:alpine

COPY --from=builder /app/dist/fintech-frond/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
